version: '3.7'

services:

  coronaz-frontend:
    build:
      context: ./coronaz-frontend
      dockerfile: Dockerfile
    volumes:
      - './coronaz-frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=lococom
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - '27017-27019:27017-27019'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass